name: Daily Expiration Cleanup

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  remove-expired-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Node.js Cleanup Script
        run: node cleanUp.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/
          
          # التحقق من وجود تعديلات فعلية قبل الرفع
          if ! git diff-index --quiet HEAD; then
            console.log("Found the tag in file:", file);
            git commit -m "chore: removed expired #new tags based on publishDate"
            git push
            echo "✅ Changes pushed successfully!"
          else
            echo "⚠️ No expired tags found to clean up."
          fi